- hosts:
    - localhost

  vars:
    deploy_file: "{{ file_name_deploy }}"
    path_file: "{{ path_to_yaml }}"
    final_deploy: "{{ final_name }}"
    app_name: "{{ my_app }}"
    img_name: "{{container_image}}"
    deployment_enabled: "{{ true_false }}"

  tasks:

    - name: ensure manifest dir exists
      file:
        path: "{{path_file}}"
        state: directory

    #- name: kubectl get secrets
    #  shell: kubectl get secrets
    #  register: kube_secrets

    - name: create manifest template for kube deploy
      template:
        src: "{{path_file}}/{{deploy_file}}"
        dest: "{{path_file}}/{{final_deploy}}"
      register: deploy_template

    # Applys
    - block:
        - name: apply kubernetes deployment
          shell: "kubectl apply -f {{path_file}}/{{final_deploy}}"
          register: script_output
        - name: 'Test new deploy'
          shell: "kubectl -n {{ app_name }} rollout status deployment.v1.apps/{{ app_name }}"
          register: deploy_status
          failed_when: deploy_status.rc > 0
        - name: 'Output to json'
          local_action:
            module: lineinfile
            dest: output.json
            line: '{{ deploy_status.stdout }}'
            create: yes
      when: deployment_enabled | bool

    # Removals
    - block:
        - name: rollback kubernetes deployment
          shell: "kubectl -n {{ app_name }} rollout undo deployment.v1.apps/{{ app_name }}"
          register: roleback_kube_deployment
      when: not deployment_enabled | bool